### PR TITLE
Port qursers to Windows

### PR DESCRIPTION
**Pull request by Willy-JL**
Title says it all :P

### CODE REVIEW

**Comment by qube-03** [comment]
trying to figure out how to put this in the windows branch holup

**Comment by Willy-JL** [comment]
@qube-03 changed the base, now merging should go into windows branch

**Comment by qube-03** [comment]
bruh wtf how, thanks tho lol

**Comment by Willy-JL** [comment]
> bruh wtf how, thanks tho lol

Edit button next to the title also allows changing the base into which you're merging :P (idk if you can do it but the PR author surely can)

Might be a good idea to move the files from inside the folder now since its in its own branch, I hadn't thought of that lol

**Pull request merged**
